app:
    resource: "@AppBundle/Controller/"
    type:     annotation


# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
    path:     /home
    defaults: { _controller: AppBundle:Default:home }
