

# ---------------------> LOGIN/NEW USER <---------------------
user_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
    path:     /home
    defaults: { _controller: AppBundle:Default:home }

user_register:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

mission:
    path:     /mission
    defaults: { _controller: AppBundle:Default:mission }

